services:
  pathfinding-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pathfinding-visualizer
    ports:
      - "80:80"
    volumes:
      # Volume for nginx configuration
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Volume for static files
      - build-volume:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - pathfinding-network

volumes:
  build-volume:
  node_modules:

networks:
  pathfinding-network:
    driver: bridge