
services:
  pathfinding-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pathfinding-visualizer
    ports:
      - "80:80"
    volumes:
      # Volume for nginx configuration
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Volume for static files
      - build-volume:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - pathfinding-network

  # Development service (optional, uncomment if you want hot-reloading during development)
  # pathfinding-dev:
  #   build:
  #     context: .
  #     target: builder
  #   container_name: pathfinding-visualizer-dev
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./src:/app/src
  #     - ./public:/app/public
  #     - ./index.html:/app/index.html
  #     - ./vite.config.ts:/app/vite.config.ts
  #     - ./tailwind.config.js:/app/tailwind.config.js
  #     - ./postcss.config.js:/app/postcss.config.js
  #     - node_modules:/app/node_modules
  #   command: npm run dev
  #   environment:
  #     - VITE_HOST=0.0.0.0
  #   networks:
  #     - pathfinding-network

volumes:
  build-volume:
  node_modules:

networks:
  pathfinding-network:
    driver: bridge